/*
 * @Author: Azhou
 * @Date: 2021-05-11 23:09:33
 * @LastEditors: Azhou
 * @LastEditTime: 2021-06-15 15:23:36
 */
export const UPDATE_USER_DETAIL = 'UPDATE_USER_DETAIL'
export const UPDATE_CURRENT_USER_PROJECTS = 'UPDATE_CURRENT_USER_PROJECTS'
export const UPDATE_CURRENT_USER_PROJECTS_LENGTH = 'UPDATE_CURRENT_USER_PROJECTS_LENGTH'
export const UPDATE_USER_LOGIN = 'UPDATE_USER_LOGIN'

export const CLEAR_PROJECT_STATE = 'CLEAR_PROJECT_STATE'

export const UPDATE_PROJECT_DETAIL = 'UPDATE_PROJECT_DETAIL'
export const UPDATE_CURRENT_PROJECT_GROUPS = 'UPDATE_CURRENT_PROJECT_GROUPS'
export const UPDATE_PROJECT_MODELS = 'UPDATE_PROJECT_MODELS'

export const UPDATE_CURRENT_GROUP = 'UPDATE_CURRENT_GROUP'
export const UPDATE_CURRENT_GROUP_IMAGES = 'UPDATE_CURRENT_GROUP_IMAGES'
export const UPDATE_CURRENT_GROUP_LENGTH = 'UPDATE_CURRENT_GROUP_LENGTH'

export const UPDATE_CURRENT_IMAGE = 'UPDATE_CURRENT_IMAGE'
export const UPDATE_CURRENT_GROUP_IMAGE_LENGTH = 'UPDATE_CURRENT_GROUP_IMAGE_LENGTH'
export const UPDATE_CURRENT_IMAGE_SIZE = 'UPDATE_CURRENT_IMAGE_SIZE'
export const UPDATE_PATHOIMGINFO = 'UPDATE_PATHOIMGINFO'
export const UPDATE_PATHOVIEWSIZE = 'UPDATE_PATHOVIEWSIZE'
export const UPDATE_CURRENT_INDEX = 'UPDATE_CURRENT_INDEX'

export const UPDATE_CURRENT_CANVAS = 'UPDATE_CURRENT_CANVAS'
export const UPDATE_CURRENT_ACTIVE_OBJ = 'UPDATE_CURRENT_ACTIVE_OBJ'
export const UPDATE_CURRENT_VIEWER = 'UPDATE_CURRENT_VIEWER'
export const UPDATE_ANNOTION = 'UPDATE_ANNOTION'
export const UPDATE_NEW_ANNOTATION = 'UPDATE_NEW_ANNOTATION'
export const UPDATE_CURRENT_ANNOTION = 'UPDATE_CURRENT_ANNOTION'
export const UPDATE_PROJECDT_ENTITY = 'UPDATE_PROJECDT_ENTITY'
export const UPDATE_CUSTOM_ENTITY = 'UPDATE_CUSTOM_ENTITY'
export const UPDATE_CURRENT_ENTITY = 'UPDATE_CURRENT_ENTITY'
export const UPDATE_CURRENT_SHAPE = 'UPDATE_CURRENT_SHAPE'
export const UPDATE_CURRENT_TRAPATHWAY = 'UPDATE_CURRENT_TRAPATHWAY'
export const UPDATE_CURRENT_INTEPATHWAY = 'UPDATE_CURRENT_INTEPATHWAY'
export const UPDATE_CURRENT_MODEL_INFERENCE = 'UPDATE_CURRENT_MODEL_INFERENCE'
export const UPDATE_CURRENT_CONTROL_TYPE = 'UPDATE_CURRENT_CONTROL_TYPE'
export const UPDATE_INIT_BOUNDING_BOX = 'UPDATE_INIT_BOUNDING_BOX'
export const UPDATE_BOUNDING_BOX_MAP = 'UPDATE_BOUNDING_BOX_MAP'
export const UPDATE_CURRENT_CLASSIFY_INFO = 'UPDATE_CURRENT_CLASSIFY_INFO'
export const UPDATE_STROKEWIDTH = 'UPDATE_STROKEWIDTH'
export const UPDATE_CIRCLERADIUS = 'UPDATE_CIRCLERADIUS'
export const UPDATE_ISEDIT = 'UPDATE_ISEDIT'
export const UPDATE_ISMUTITAG = 'UPDATE_ISMUTITAG'
export const UPDATE_LAUNCH_REF_PROCESS = 'UPDATE_LAUNCH_REF_PROCESS'
export const UPDATE_SEGPOSITIVE = 'UPDATE_SEGPOSITIVE'
export const UPDATE_SAMMODE = 'UPDATE_SAMMODE'
export const UPDATE_CANNYTHRESHOLD = 'UPDATE_CANNYTHRESHOLD'
export const UPDATE_THRESHOLD = 'UPDATE_THRESHOLD'
export const UPDATE_CURRENT_MODEL_INFO = 'UPDATE_CURRENT_MODEL_INFO'







